variable "vpc_cidr" {}
variable "enable_dns_support" {}
variable "enable_dns_hostnames" {}
variable "web_subnet_count" {}
variable "app_subnet_count" {}
variable "db_subnet_count" {}
variable "reserved_subnet_count" {}
variable "web_cidr_blocks" {}
variable "app_cidr_blocks" {}
variable "db_cidr_blocks" {}
variable "reserved_cidr_blocks" {}
variable "max_subnetcount" {}
variable "vpc_endpoints" {}
variable "security_group_ids" {}
variable "availability_zone" {}
variable "service_name" {}
variable "vpc_endpoint_type" {}