variable "instance_type" {}
variable "vpc_id" {}
variable "security_groups" {}
variable "web_user_data" {}
variable "app_user_data" {}
variable "iam_managed_policy_s3" {}
variable "iam_managed_policy_ssm" {}
variable "ami_filter_name" {}
variable "ami_filter_architecture" {}
variable "ami_owner" {}
variable "iam_role_trust_policy" {}
variable "sg_egress_cidr" {}
variable "sg_egress_from_port" {}
variable "sg_egress_to_port" {}
variable "sg_egress_Protocol" {}
variable "app_sg_name" {}
variable "app_sg_description" {}
variable "app_sg_from_port" {}
variable "app_sg_to_port" {}
variable "app_sg_protocol" {}
variable "appserver_ami_id" {}
variable "db_sg_name" {}
variable "db_sg_description" {}
variable "db_sg_from_port" {}
variable "db_sg_to_port" {}
variable "db_sg_protocol" {}
variable "rds_endpoint" {}
variable "rds_username" {}
variable "rds_password" {}